README.rst, ftw/theming/resources/scss/default_variables.scss
Inludes mixins for phone, tablet, desktop, etc.
=> Add media queries for some common viewports.

ftw/theming/resources/scss/default_variables.scss, ftw/theming/tests/test_controlpanel.py
Got shades from
http://www.colourlovers.com/palette/345774/Shades_of_Gray
Not using black for textcolor is better for reading.
=> Use other shades of grey.

ftw/theming/resources/scss/default_variables.scss, ftw/theming/resources/scss/standard_mixins.scss
The ```noselect``` mixin prevents the user from selecting element.
=> Define noselect and print media mixin.

ftw/theming/resources/scss/default_variables.scss, ftw/theming/resources/scss/standard_mixins.scss
=> Add button scss mixin

README.rst
=> Correcting typos

docs/HISTORY.txt, ftw/theming/configure.zcml
Also provide the custom catalog brain content icon adapter for solr
flairs.
https://github.com/collective/collective.solr/blob/master/src/collective/solr/configure.zcml#L63-L68
=> Provide mimetype icons for solr flairs.

docs/HISTORY.txt, ftw/theming/resources/scss/base/standard_icons.scss
=> Add open office mimetype icons.

docs/HISTORY.txt, ftw/theming/resources/scss/elements/list-group.scss, ftw/theming/resources/scss/globals/grid.scss
=> Implement floated grid.

ftw/theming/resources/scss/elements/form.scss, ftw/theming/resources/scss/elements/list-group.scss, ftw/theming/resources/scss/elements/tab.scss, ftw/theming/resources/scss/globals/grid.scss, ftw/theming/resources/scss/globals/helpers.scss
Example of tab in plonetheme.blueberry
=> General improvements.

ftw/theming/resources/scss/elements/list-group.scss, ftw/theming/resources/scss/elements/tab.scss
=> Tab list element gains additional height.

docs/HISTORY.txt, ftw/theming/resources.zcml, ftw/theming/resources/scss/elements/label.scss, ftw/theming/resources/scss/globals/variables.scss
=> Add label element mixins.

ftw/theming/resources/scss/elements/button.scss, ftw/theming/resources/scss/elements/list-group.scss, ftw/theming/resources/scss/globals/grid.scss, ftw/theming/resources/scss/globals/helpers.scss, ftw/theming/resources/scss/globals/variables.scss, ftw/theming/resources/scss/iconset_font-awesome.scss
- Link icon width with base lineheight.
- Decrease the secondary box-shadow.
- Increase the default base lineheight.
- Introduce pixel to em converter.
- Handle visited links in the `nolink` mixin.
- Define default values for the floatgrid.
- Handle visited links in the `list-group-item-interactive` mixin.
- Handle visited links in the button mixin.
=> Several improvements

docs/HISTORY.txt, ftw/theming/resources.zcml, ftw/theming/resources/scss/elements/progressbar.scss, ftw/theming/resources/scss/globals/helpers.scss
=> Introduce progressbar mixin.

ftw/theming/resources/scss/elements/label.scss, ftw/theming/resources/scss/elements/list.scss, ftw/theming/resources/scss/globals/helpers.scss, ftw/theming/resources/scss/iconset_font-awesome.scss
=> rounded labels, trees and small fixes

ftw/theming/resources.zcml, ftw/theming/resources/scss/elements/list.scss, ftw/theming/resources/scss/elements/portrait.scss, ftw/theming/resources/scss/globals/grid.scss
=> Introduce portrait mixin.

ftw/theming/resources.zcml, ftw/theming/resources/scss/elements/overlay.scss
Introduce four different overlay styles based on the predicted content of the overlay.
=> Introduce overlay mixin.

docs/HISTORY.txt, ftw/theming/resources/scss/elements/tab.scss
This enables support for jquerytools tabs.
=> Support selected state of tab-list on link (a tag) too.

docs/HISTORY.txt, ftw/theming/resources/scss/globals/helpers.scss
Update the `ie-only` selector so it is able to support IE11 and ms edge.
=> Use 'ms-lang' selector for ie-only

docs/HISTORY.txt, ftw/theming/resources/scss/globals/variables.scss
These changes make it possible to use the font family definition
in diffrent packages and themes.
=> Take font family definition from plonetheme.blueberry

ftw/theming/resources/scss/elements/progressbar.scss, ftw/theming/resources/scss/globals/helpers.scss
Introduce more specific gradient mixin.
Introduce transform mixin with vender prefixes.
=> Helper enhancements.

docs/HISTORY.txt, ftw/theming/resources.zcml, ftw/theming/resources/scss/globals/zindex.scss
See https://github.com/4teamwork/plonetheme.blueberry/pull/69
=> Move zindex system from plonetheme.blueberry

docs/HISTORY.txt, ftw/theming/resources/scss/globals/helpers.scss
Introduce appearance helper to cover all necessary browser vender prefixes.
=> Introduce appearance helper

docs/HISTORY.txt, ftw/theming/resources/scss/elements/tab.scss
The tab is now able to have a background color for both active, hover and normal state.
=> Provide background option for tab-list mixin

ftw/theming/resources/scss/globals/helpers.scss
I do not add another changelog entry. The previous one already relates to this issues.
Closes https://github.com/4teamwork/ftw.theming/issues/78
=> Include chrome fallback in hyphenation mixin

docs/HISTORY.txt, ftw/theming/resources/scss/globals/helpers.scss
Closes https://github.com/4teamwork/ftw.theming/issues/81
This mixin applies to safari and chrome.
=> Introduce webkit-only helper mixin.
