- README.rst
- ftw/theming/browser/theming_variables.py
- ftw/theming/compiler.py
- ftw/theming/extensions.py
- ftw/theming/utils.py
- setup.py
Add embed-resource function for embedding svgs.
The embed-resource function is able to fill svgs based on
css and xpath selectors.
Be aware that SVGs are namespaced (!) XMLs, therefore it is quite
hard to find the right selector and not all CSS selectors may be
convertable to XPath.
> embed-resource function

- ftw/theming/browser/theming_css.py
- ftw/theming/tests/test_theming_css_view.py
- ftw/theming/viewlets/theming_css.py
The theming.css is now cached in the browser cached because we set cache
control headers.
In order to be able to invalidate the cache we add a cachekey param to
the css url, so that we just can change the param and thus the URL in
order to invalidate the cache.
The cachekey is generated per navigation root and contains the URL to
the navigation root, a portal_css bundle compilation state hash and the
modified date of the navigation root.
The cachekey changes when the portal_css bundles are recooked or when
the navigation root is changed.
When the portal_css debug mode is enabled, caching is disabled
altogether by not appending a cachekey param.
Removed cache-invalidation on shift-reload because any user can
invalidate the server-side cache and force a sass compilation, which is
in fact a …
> Implement client-side caching.

- ftw/theming/browser/configure.zcml
- ftw/theming/browser/theming_css.py
- ftw/theming/tests/test_theming_css_view.py
- ftw/theming/viewlets/theming_css.py
The theming.css may be requested on any context.
In order to make the client-side cache work efficiently we only want to
have theming.css-requests on navigation roots.
Therefore all requests on non-navigation-roots are redirected to the
next parent navigation root, adding the cachekey param.
This fixes a TinyMCE problem:
When "theming.css" is configured as TinyMCE content CSS resource, it is
requested relative to the current context, which breaks caching because
the URL always changes.
@maethu please take a look
> add theming.css redirect on non-navroots

- ftw/theming/resources/scss/default_variables.scss
The fallbackfont in the normalize css is set to ```serif```. If the host system has no font for this definition some chars which are not defined in the base font family are not displayed correctly. So the most save font for the web is ```Times```.
> Define fallbackfont variable.

- ftw/theming/browser/theming_css.py
- ftw/theming/compiler.py
- ftw/theming/interfaces.py
- ftw/theming/profileinfo.py
- ftw/theming/registry.py
- ftw/theming/resource.py
- ftw/theming/tests/test_compiler.py
- ftw/theming/tests/test_file_resource.py
- ftw/theming/tests/test_profileinfo.py
- ftw/theming/tests/test_resource.py
- ftw/theming/tests/test_theming_css_view.py
In order to make development faster we cache the compiled CSS even when the debug mode is active.
When the debug mode is active we include a cachekey for each resource which changes when any file or result of a dynamic resource has changed.
The developer does not need to care about the cache. When in doupt, a shift-reload does always recompile.
Also use md5 instead of base64 for the cachekey in order to avoid newlines.
> Caching in development mode

- ftw/theming/resources/scss/standard_mixins.scss
Statements like...
```scss
@include boxshadow(0 1px 1px transparentize($input-focus-color, .8) inset,
0 0 5px transparentize($input-focus-color, .6));
}
```
.. are valid now. 
See http://stackoverflow.com/questions/7517941/pass-a-list-to-a-mixin-as-a-single-argument-with-sass
> The boxshadow mixin needs to take a variable arguments.

- ftw/theming/browser/configure.zcml
- ftw/theming/browser/theming_css.py
- ftw/theming/interfaces.py
Depending on the generated CSS, Zope's GZIP compression will fail and result in an invalid response.
In order to mitigate this issue we no longer use ``enableHTTPCompression``.
By configuring a plone.app.caching ruleset we can let plone.app.caching handle the compression, when it is installed and configured.
It will also override the Cache-Control header.
In order to have a Cache-Control header when p.a.caching is not installed or not configured, we still set it.
> Fix an error when gzipping the CSS.

- README.rst
- ftw/theming/browser/theming_css.py
- ftw/theming/compiler.py
- ftw/theming/interfaces.py
- ftw/theming/registry.py
- ftw/theming/resource.py
- ftw/theming/tests/__init__.py
- ftw/theming/tests/test_compiler.py
- ftw/theming/tests/test_registry.py
- ftw/theming/tests/test_resource.py
- ftw/theming/tests/test_theming_css_view.py
- ftw/theming/variables.py
Until now, the resource cache keys are only included in development. The idea is that the source does not change when there is no update. Recooking (`portal_css`) will update the cache.
But dynamic resources can change at any given time and demand to be respected in production too.
There is now a new `DynamicSCSSResource` base class, of which the cache key is also used in production.
Background:
In production, we dont want to ask all resources for their cache keys. Getting all resources will also apply ordering and conditions, which is quite slow. Therefore we use the full, slow keys and lookups in development and to as few as possible in production. This has the side effect that in production all dynamic resources are always asked for their cachekeys in an unordered manner without …
> Change caching to include dynamic resource cache keys in production

- ftw/theming/browser/theming_css.py
- ftw/theming/tests/test_theming_css_view.py
The get_url() method on the theming.css view returns the full URL to the
theming.css relative to the nearest navigation root with caching
parameters.
It can be used in custom templates, e.g.:
```xml
<link rel="stylesheet" type="text/css" tal:attributes="href string:context/theming.css/get_url" />
```
Closes #14
> add get_url() to theming.css view.

- setup.py
Fixes:
```python
Traceback:
File "..../eggs/pyScss-1.3.4-py2.7.egg/scss/compiler.py", line 374, in manage_children
self._manage_children_impl(rule, scope)
File "..../eggs/pyScss-1.3.4-py2.7.egg/scss/compiler.py", line 408, in _manage_children_impl
self._get_properties(rule, scope, block)
File "..../eggs/pyScss-1.3.4-py2.7.egg/scss/compiler.py", line 1107, in _get_properties
value = calculator.calculate(raw_value, divide=True)
File "..../eggs/pyScss-1.3.4-py2.7.egg/scss/calculator.py", line 116, in calculate
result = self.evaluate_expression(expression, divide=divide)
File "..../eggs/pyScss-1.3.4-py2.7.egg/scss/calculator.py", line 134, in evaluate_expression
ast = self.parse_expression(expr)
File "..../eggs/pyScss-1.3.4-py2.7.egg/scss/calculator.py", line 167, in parse_expression
ast = …
```
> add six constraint to version having six.unichr.

- ftw/theming/browser/icons.py
- ftw/theming/browser/templates/icons.pt
- ftw/theming/configure.zcml
- ftw/theming/icons.py
- ftw/theming/resources/scss/base/standard_icons.scss
- ftw/theming/resources/scss/default/theming_controlpanel.scss
- ftw/theming/resources/scss/default_variables.scss
- ftw/theming/resources/scss/icon_mixins.scss
- ftw/theming/resources/scss/iconset_font-awesome.scss
- ftw/theming/tests/test_controlpanel.py
- ftw/theming/tests/test_icons.py
- extend Plone's `IContentIcon` adapter to return a `span`-wrapper where we can place the font-awesome-icon in a before
- add registry for icons and flag for portal-types which have mimetype icons (`File` only by default)
- add default icons
- show icons in controlpanel
**Result:**
Folder contents, navigation and factories-menu:
--
Simplelayout file listing block with ftw.table (https://github.com/4teamwork/ftw.table/pull/40), Live search (https://github.com/OneGov/plonetheme.onegovbear/pull/68):
--
Control-Panel marks types which are known to have mimetypes:
--
Control-Panel lists all mimetype icons in use:
> Use font awesome for mimetype icons

- docs/HISTORY.txt
- ftw/theming/resources/scss/iconset_font-awesome.scss
The type icon is not necessary, the mimetype icon is sufficient.
**Before:**
--
**After:**
> Remove duplicate icon in search results for files.

- docs/HISTORY.txt
- ftw/theming/resources/scss/globals/grid.scss
Fixes https://github.com/OneGov/plonetheme.onegovbear/issues/109
Add `width-full` functional class of deco grid system for legacy support.
> `width-full` functional class for grid system is not available.

- ftw/theming/resources/scss/globals/grid.scss
The inserted clearfix has the same effect as floating left.
The row should also limit in its height to match the page layout.
> Limit the row in its height.

- docs/HISTORY.txt
- ftw/theming/resources/scss/globals/variables.scss
- ftw/theming/tests/test_controlpanel.py
On some backgrounds (colored) the default link color is not visible. So introduce an inverted link color which will be used on colored backgrounds.
Change the default color scheme to a more blueberry styling scheme because the main theme is plonetheme.blueberry.
Example of the plueberry.theme
> The link color is not visible on some background.

- docs/HISTORY.txt
- ftw/theming/resources.zcml
- ftw/theming/tests/test_variables.py
- ftw/theming/variables.py
All available scales from the properties are stored in a
dynamic SCSS file.
Each scale is stored as a variable with the name of the scale.
Each variable stores a map with the dimensions.
> Register available scales in dynamic SCSS file.

- ftw/theming/resources/scss/elements/form.scss
The inputfield can growth full width in the `screen-small` view. The width is restricted above this width.
> Make inputs responsive.

- ftw/theming/resources/scss/elements/list.scss
- ftw/theming/resources/scss/elements/tab.scss
- Reduce spacing between horizontally aligned list items.
Because the list items have the standard spacing on both sides the space
between horizontally aligned list items is doubled. So use the half of the spacing.
- Tab default background should be equal to the content background.
> General Improvements

- docs/HISTORY.txt
- ftw/theming/resources/scss/elements/overlay.scss
According to https://github.com/4teamwork/plonetheme.blueberry/pull/52#issuecomment-214168577
the large overlay is too small. So we decided to make the large overlay
almost fullscreen so that the user is still able to see a bit of the
page in the transparent background.
The large overlay does not scale the size until the mobile breakpoint has been
reached.
The small overlay is too small on tiny screen becuase the height is relative to the
screensize. So we dediced to set a fixed height so that the user is still able
to see the content of the overlay on tiny screens.
We height is based on the plone login form and the simplelayout delete confirmation.
> Adjust overlay size for large and small overlay.

- docs/HISTORY.txt
- ftw/theming/resources/scss/globals/helpers.scss
See http://keithclark.co.uk/articles/moving-ie-specific-css-into-media-blocks/media-tests/
for more information about the hack.
> Introduce ie-only mixin.

- docs/HISTORY.txt
- ftw/theming/resources/scss/elements/tab.scss
The tab hover state will now always be the selected state.
> Reduce tab hover state

- README.rst
- docs/HISTORY.txt
- ftw/theming/extensions.py
The current syntax for the `embed_resource` mixin is not
valid SCSS. SCSS is only able to accept a list as an argument.
> Fix `embed_resource` mixin

- docs/HISTORY.txt
- ftw/theming/browser/icons.py
- ftw/theming/icons.py
- ftw/theming/utils.py
The problem was that when using `++resource++...` image paths in the `resource_registry`, the normalizer did crop the last parts in order to be shorter than `50`, the default `max_length`, resulting in ambiguous CSS class names.
In this event we refactored the CSS class name generator into a separate utility function.
> Fix support for mimetype icons having long names.

- docs/HISTORY.txt
- ftw/theming/resources/scss/icon_mixins.scss
Refactor the internal icon storage from list to map, so that existing icon definitions are replaced when an icon is redefined for an already defined portal type or mimetype.
Only the internal data structure and functions for using those are changed, thus backwards compatibility is ensured.
> Support replacing portal-type- and mimetype-icons.

- docs/HISTORY.txt
- ftw/theming/browser/configure.zcml
- ftw/theming/browser/theming_css.py
- ftw/theming/interfaces.py
- ftw/theming/tests/test_theming_css_view.py
plone.app.caching does not ever cache resources which are not public (View
for Anonymous).
This means that when using plone.app.caching we cannot cache the
generated CSS within unpublished navigation roots at all.
Since the CSS does not really contain any information about the
navigation root it is not a problem to cache it, and we should cache it
whenever possible since building the CSS is considered slow.
Therefore we no longer use plone.app.caching in order to set the
Cache-Control response headers. We now always do this manually.
-
theming.css: cache with public, not private.
Since the CSS does not contain any user specific data, it can safely be
cached in a public caching proxy.
> Fix caching for unpublished navigation roots

- README.rst
- docs/HISTORY.txt
- ftw/theming/resources.zcml
- ftw/theming/resources/scss/globals/fontface.scss
- ftw/theming/resources/scss/globals/helpers.scss
- ftw/theming/resources/scss/iconset_font-awesome.scss
Helpers:
- `rem`: This helper converts pixel to `rem` units.
- font-face helper: This helpers generates font face definition to support different browsers
``` scss
@include font-face($name: 'VerdanaRegular', $path: '++resource++nidau.web/fonts/Verdana');
@include font-face($name: 'VerdanaBold', $path: '++resource++nidau.web/fonts/Verdana-Bold', $weight: bold);
```
The file-extension for the `$path` argument is going to be concatenated automatically. Both `woff` and `woff2` must be provided.
produces:
``` css
@font-face {
font-family: 'VerdanaRegular';
font-style: normal;
font-weight: normal;
src: url("++resource++nidau.web/fonts/Verdana.woff2") format(woff2),
url("++resource++nidau.web/fonts/Verdana.woff") format(woff);
}
@font-face {
font-family: 'VerdanaBold';
font-style: normal; …
```
> Introduce new helper mixins

- docs/HISTORY.txt
- ftw/theming/resources/scss/base/standard_icons.scss
By marking the "Image" type to have mimetype icons we awoid duplicate icons (portal_type icon + mimetype icon).
**Before:**
**After:**
> Avoid duplicate (mimetype) icons on "Image" types.

- docs/HISTORY.txt
- ftw/theming/resources/scss/globals/grid.scss
There is enough space an a DINA4 to display two columns next to each other.
With the previous layout, the gallery is printed too large.
Closes https://github.com/4teamwork/ai.web/issues/155
> Use two columns for print layout.

- docs/HISTORY.txt
- ftw/theming/Extensions/install.py
When installing `ftw.theming` with the quickinstaller the default profile now gets installed along with the base profile.
This makes `ftw.theming` compatible with quickinstaller and allows for reinstallations.
closes #72
> Add support for installation with quickinstaller

- docs/HISTORY.txt
- ftw/theming/resources/scss/globals/fontface.scss
Before:
``` scss
@font-face {
...
src: url("http://...") format(woff2),
...
}
```
After:
``` scss
@font-face {
...
src: url("http://...") format('woff2'),
...
}
```
Notice the quotes around the format declaration.
Additionally add option to pass a unicode range as the mixin-content.
See example from GoogleFontsAPI -> https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext
> Fix escaping of fontface mixin.

- README.rst
- docs/HISTORY.txt
- ftw/theming/resources/scss/globals/variables.scss
- Remove deprecated variables.
- Define new deprecated viewport mixins and variables.
The only mixin available will be:
``` scss
@mixin screen-large
@mixin screen-medium
@mixin screen-small
```
I updated both `ftw.subsite` and `ftw.mobile` to be compatible with the newest version.
https://github.com/4teamwork/ftw.subsite/pull/103 https://github.com/4teamwork/ftw.mobile/pull/53
> Remove deprecated variables.

- docs/HISTORY.txt
- ftw/theming/icons.py
This eg. occurred for the french translations of content types in PloneFormGen.
> Fix UnicodeEncodeError error for content types with unicode characters

- docs/HISTORY.txt
- ftw/theming/configure.zcml
The set_ftw_theming_header subscriber relies on the browserlayer to be applied to the request, in order to guarantee that, the plone.browserlayer subscriber must be registered first.
> plone.browserlayer subscriber must be registered before our subscriber

- docs/HISTORY.txt
- ftw/theming/browser/icons.py
- ftw/theming/browser/templates/icons.pt
- ftw/theming/icons.py
- ftw/theming/resources/scss/base/standard_icons.scss
- ftw/theming/resources/scss/icon_mixins.scss
- ftw/theming/resources/scss/iconset_font-awesome.scss
- ftw/theming/tests/__init__.py
- ftw/theming/tests/test_controlpanel.py
- ftw/theming/tests/test_file_resource.py
- ftw/theming/tests/test_icons.py
- ftw/theming/tests/test_registry.py
- ftw/theming/tests/test_resource.py
- ftw/theming/tests/test_scss_directive.py
- ftw/theming/tests/test_uninstall.py
- ftw/theming/utils.py
Up to now, ftw.theming used the "getIcon" catalog column (containing an image path) for generating a HTML structure which can be styled with CSS / font awesome icons.
This strategy does no longer work well in Plone 5 since the "getIcon" metadata column is no longer used.
This change adds an additional strategy for when there is no "getIcon" value on the brain. The new strategy uses the "mime_type" column for generating a css class. This strategy may not work well with Plone 4 / depending on the configuration, that's why we no have two strategies.
Since the strategies generated varying css classes, the icons need to be re-defined based on the "mime_type" value in addition to the definition based on the "getIcon" filename.
The change includes icon definitons for the already styled mimetypes …
> Improve mimetype icons support for better Plone 5 support.

- docs/HISTORY.txt
- ftw/theming/icons.py
The icon wrapper was [recently extended](https://github.com/4teamwork/ftw.theming/pull/90) to also support catalog's `mime_type` metadata.
But the `mime_type` metadata was introduced with Plone 5 and is not available with Plone 4.
That's why we need a fallback which does not wrap `getImage`.
These cases are now implemented:
- when `getIcon` is set, use the URL in the `CatalogBrainContentIcon` image tag
- use `brain.mime_type` (only Plone 5)
- fallback to wrapper (Plone 4 without `getIcon`).
I couldn't write a realiable test though. I think it depends on the Plone 4 minor version wether it is reproducible. Tests of other packages are failing at the moment because of that problem and will recover, proving that this solution works.
> Fix mimetype icon problem for Plone 4 when there is no icon defined.
